### PR TITLE
Fix lend buttons in all views; closes #198

### LINKED ISSUE #198: Ensure that minimum project amount is $25, and funded projects can't be lended to. If have less than $10 less, allow lender to fill that.

### PR DESCRIPTION
**Pull request by EmilyMB**
This fixes all the lend buttons to hide them when the project is fully funded or inactive and change the amount if less than $25 is needed.

Changes include:
* Pull lend button into partial to ensure uniformity
* Create new factory (tenant_visible with attributes approved & active both true) to use this as the default for the project factory
* Ensure that users can not visit the tenant_path for unapproved and/or inactive tenants

### CODE REVIEW

File: app/controllers/tenants/projects_controller.rb [hunk 1]
```diff
@@ -1,7 +1,10 @@
 class Tenants::ProjectsController < ApplicationController
 
   def index
-    @tenant = Tenant.find_by(slug: params[:slug])
+    @tenant = Tenant.where(slug: params[:slug]).
+                     where(active: true).
+                     where(approved: true).first
+
```
Comment (mikedao) [inline app/controllers/tenants/projects_controller.rb]: Good deep search.

File: app/views/shared/_lend_button.html.erb [hunk 2]
```diff
@@ -0,0 +1,10 @@
+<% if project.visible %>
+  <div class="lend-button">
+    <%= form_for :pending_loan, url: pending_loan_path do |f| %>
+      <%= f.hidden_field :project_id, value: project.id %>
+      <%= f.hidden_field :loan_amount,
+      value: [2500, project.current_amount_needed].min %>
+      <%= f.submit "Lend $#{[25, project.current_amount_needed / 100].min}", class: "btn btn-default" %>
```
Comment (oorion) [inline app/views/shared/_lend_button.html.erb]: I like this logic
