### PR TITLE
Fix tenant slug; closes #130

### LINKED ISSUE #130: create test to fix tenants page slug
ensure slug, not org name

### PR DESCRIPTION
**Pull request by EmilyMB**
Fixed tests and layouts to ensure that tenant paths make use of the tenant slug (the parameterized version of the org name), rather than the org name itself.

Changes include:
* Update factories to include a organization name with spaces to ensure that parameterization is working.
* Update pending_loans test to include slug rather than organization
* Slight cleanup of routes file 
* Update categories/show page to use slug, rather than org name.

### CODE REVIEW

File: config/routes.rb [hunk 1]
```diff
@@ -10,12 +10,7 @@
 
   get "/choose", to: "static_pages#choose"
 
-  resource :pending_loan, only: [:show, :create, :destroy, :update]
-  # post "/pending_loans", to: "pending_loans#create"
-  # delete "/pending_loans", to: "pending_loans#destroy"
-  # get "/pending_loan", to: "pending_loans#show"
-  # delete "/pending_loan", to: "pending_loans#delete_pending_loan",
-  #                         as: "delete_pending_loan"
+  resource :pending_loan, except: [:index, :edit]
```
Comment (oorion) [inline config/routes.rb]: should this be resource pending_loans?

Comment (oorion) [inline config/routes.rb]: upon further discussion, this is ok for now.
