### PR TITLE
Skip all failing tests; closes #97

### LINKED ISSUE #97: Skip all failing tests
We are at the point that we really need to make sure that additional features are not breaking functionality, so I am skipping all failing tests.

### PR DESCRIPTION
**Pull request by EmilyMB**
In order to prevent breaking functionality moving forward, I have skipped all failing tests.

From now on, all tests should be passing(or skipped) before submitting a pull request. Test by test, we will need to work through the skipped tests.

### CODE REVIEW

File: test/factories/factories.rb [hunk 1]
```diff
@@ -15,7 +15,7 @@
     password "password"
     sequence(:street) { |n| "412#{n} Tasty Animals Lane" }
     city "new york"
-    email "test@test.com"
+    sequence(:email) { |n| "test#{n}@test.com" }
```
Comment (EmilyMB) [inline test/factories/factories.rb]: Needed to add this since per @mikedao's changes, user emails need to be unique.

**Comment by AdamSmith910** [comment]
Everything looks great.  Thank you for doing this.
