### PR TITLE
Added test, fixed unintended bugs. closes #96

### LINKED ISSUE #96: Chore: fix user registration tests

### PR DESCRIPTION
**Pull request by mikedao**
This is a maintenance PR. 

* Using the session to store tenant id on signup was a GREAT idea. (Because it was mine), but it had some unintended consequences of the tenant_id persisting if signup wasn't complete or if it failed. Now, the session[:tenant_id] will be cleared when the user clicks on Signup.

* I made an error in refactoring. Pulled logic out into a new method, but never actually calling said method. Whoops.  Added a test for this method so it won't happen again.

* Removing the roles and enums made other things fail. Created an admin? method in the user model so our Nav bar would stop freaking out.

* Added a test that covers user#admin? method.

### CODE REVIEW

File: test/integration/user_signup_test.rb [hunk 1]
```diff
@@ -108,4 +108,31 @@ class CreateAUserTest < ActionDispatch::IntegrationTest
     assert_equal root_path, current_path
     assert page.has_content?("Thank you for creating an account.")
   end
+
+  test "a user cannot sign up with a non unique email address" do
+    create(:user)
```
Comment (mikedao) [inline test/integration/user_signup_test.rb]: This is two spaces. I don't know?

Comment (EmilyMB) [inline test/integration/user_signup_test.rb]: Certainly looks like :two: to me!

File: app/controllers/static_pages_controller.rb [hunk 2]
```diff
@@ -1,4 +1,5 @@
 class StaticPagesController < ApplicationController
   def choose
+    session[:tenant_id] = nil
```
Comment (EmilyMB) [inline app/controllers/static_pages_controller.rb]: Hehe! I love seeing my ideas implemented :smile:

File: app/controllers/users_controller.rb [hunk 3]
```diff
@@ -4,6 +4,7 @@ def new
 
   def create
     if User.find_by(new_email)
+      duplicate_email
```
Comment (EmilyMB) [inline app/controllers/users_controller.rb]: I guess this is fine, but I wonder if in real life it's more common for people to try to re-sign up for something or for them to incorrectly type their own email and put in someone else's? Maybe the latter, which means that your logic is the way to go.

Comment (mikedao) [inline app/controllers/users_controller.rb]: I dont see the problem - I thought spec was no duplicate emails?

File: test/models/user_test.rb [hunk 4]
```diff
@@ -111,4 +111,10 @@ class UserTest < ActiveSupport::TestCase
     assert user.lender?
     refute user.borrower?
   end
+
+  test "it is not an admin" do
```
Comment (EmilyMB) [inline test/models/user_test.rb]: Don't let the :space_invader: who signs up be an admin!

File: app/controllers/users_controller.rb (hunk 3 above)
Comment (EmilyMB) [inline app/controllers/users_controller.rb]: No, no problem. It was just a thought exercise about frequency of errors.

File: app/controllers/static_pages_controller.rb (hunk 2 above)
Comment (mikedao) [inline app/controllers/static_pages_controller.rb]: :sparkles:
