### PR TITLE
Fix seed file; closes #129

### LINKED ISSUE #129: create lender and borrower in seed file
This should be username: lender, password:password
and
username: borrower
password: password
Both borrower and lender should have projects

### PR DESCRIPTION
**Pull request by EmilyMB**
This PR includes a number of changes to the seed file to match the spec, specifically: 
* At least 10 total businesses (tenants)
* At least 20 listings per business (projects)
* At least 5 listing categories (categories)
* 100 known customers (users, as lenders)
* 2 business admins per business (users, as borrowers)
* 2 platform administrators (admins)

### CODE REVIEW

File: db/seeds.rb [hunk 1]
```diff
@@ -1,80 +1,32 @@
...
+    email:                 "FlowersNPuppies-#{n + 1}@example.com",
+    password:              "password",
+    password_confirmation: "password",
+    first_name:            Faker::Name.first_name,
+    last_name:             Faker::Name.last_name,
+    city:                  "Atlanta",
+    state:                 "GA",
+    zipcode:               50240,
+    street:                "6#{n + 1}#{n + 2} Mockingbird Lane",
+    country:               Faker::Address.country,
```
Comment (EmilyMB) [inline db/seeds.rb]: I am leaving the extra spacing so that all the variables are lined up.

**Comment by mikedao** [comment]
I just want to confirm, we have an admin named admin, borrower named borrower and user named lender, right?

**Comment by EmilyMB** [comment]
@mikedao: yes, admin as admin, borrower as borrower, and lenders (user with no associated tenant) as lender1...lender100
